import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kanto Cocktail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer className="w-full text-center p-4 bg-black ">
        <p className="text-white pb-2">Enjoy responsibly. All cocktails designed for Kanto Cocktail.</p>
        <p className="text-sm font-bold text-red-500">Warning: May cause spontaneous karaoke sessions.</p>
      </footer>
    </html>
  );
}
